name: inventory_app
description: "Inventory App by AMALWorks"
publish_to: 'none'
version: 1.0.1+6

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  android_intent_plus: ^5.0.2
  badges: ^3.1.2
  csv: ^6.0.0
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  intl: ^0.19.0
  media_store_plus: ^0.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/scarf.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_blue.png"
  adaptive_icon_background: "assets/icons/logo_blue.png"
  adaptive_icon_foreground: "assets/icons/logo_transparent.png"