name: inventory_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  android_intent_plus: ^5.0.2
  badges: ^3.1.2
  csv: ^6.0.0
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/scarf.jpg